import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import type mongoose from 'mongoose';
import User from '../models/User.js';
import Project from '../models/Project.js';
import logger from '../utils/logger.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '../..');
const KEY_FILE = path.join(ROOT_DIR, '.dashboard-key');
const WEB_ENV_FILE = path.join(ROOT_DIR, 'web', '.env.local');

const DEFAULT_PROJECT_NAME = 'ResumeForge Demo';
const DEFAULT_USER_EMAIL = 'admin@resumeforge.local';

/**
 * Seed a default user + project with an API key on startup (idempotent).
 * Writes the API key to `.dashboard-key` and auto-updates `web/.env.local`.
 */
export async function seedDefaultProject(): Promise<void> {
  // Check if a project already exists
  const existingProject = await Project.findOne({ name: DEFAULT_PROJECT_NAME });
  if (existingProject && existingProject.apiKeys?.length > 0) {
    const key = existingProject.apiKeys[0]!.key;
    logger.info('Default project exists', { apiKey: key });
    ensureFrontendKey(key);
    return;
  }

  // Create or find the default user
  let user = await User.findOne({ email: DEFAULT_USER_EMAIL });
  if (!user) {
    user = await User.create({
      email: DEFAULT_USER_EMAIL,
      name: 'Admin',
      passwordHash: 'seeded-no-login', // Dashboard admin, no real auth yet
    });
    logger.info('Seeded default user', { email: DEFAULT_USER_EMAIL });
  }

  // Create project with an auto-generated API key
  const project = await Project.create({
    name: DEFAULT_PROJECT_NAME,
    owner: user._id as mongoose.Types.ObjectId,
    apiKeys: [{ label: 'Dashboard Key' }], // key auto-generated by schema
    plan: 'free',
    webhookUrl: null,
  });

  const key = project.apiKeys[0]!.key;

  // Write key to a file for automation
  fs.writeFileSync(KEY_FILE, key, 'utf-8');
  logger.info(`Seeded default project with API key: ${key}`);
  logger.info(`  → Key written to ${KEY_FILE}`);

  // Auto-update the frontend .env.local
  ensureFrontendKey(key);
}

/**
 * Ensure `NEXT_PUBLIC_API_KEY` is set in `web/.env.local`.
 */
function ensureFrontendKey(key: string): void {
  try {
    let content = '';
    if (fs.existsSync(WEB_ENV_FILE)) {
      content = fs.readFileSync(WEB_ENV_FILE, 'utf-8');
    }

    if (content.includes('NEXT_PUBLIC_API_KEY=')) {
      // Update existing value
      const updated = content.replace(/NEXT_PUBLIC_API_KEY=.*/, `NEXT_PUBLIC_API_KEY=${key}`);
      if (updated !== content) {
        fs.writeFileSync(WEB_ENV_FILE, updated, 'utf-8');
        logger.info('Updated NEXT_PUBLIC_API_KEY in web/.env.local');
      }
    } else {
      // Append
      const separator = content.endsWith('\n') || content === '' ? '' : '\n';
      fs.writeFileSync(
        WEB_ENV_FILE,
        `${content}${separator}\n# ── Dashboard API Key (auto-generated) ──────────\nNEXT_PUBLIC_API_KEY=${key}\n`,
        'utf-8',
      );
      logger.info('Added NEXT_PUBLIC_API_KEY to web/.env.local');
    }
  } catch {
    logger.warn('Could not update web/.env.local — set NEXT_PUBLIC_API_KEY manually');
  }
}
